### PR TITLE
Add feature for HTML extraction/saving and bugfix of d3/jQuery dead link

### PR DESCRIPTION
**Pull request by cyber-raskolnikov**
I have contributed by:

1. Adding support to retrieve the HTML representations of model, head and neuron views. This feature is documented at the updated README. This is useful if you want to save them as html files for web browser visualization or for custom display functions as it is the case in the Databricks platform, where the visualizations didn't work previously.

2. There was a dead requirement URL in the .js files of the views, regarding the d3/jQuery requirement. I have updated it as it caused issued when trying to visualize the visualizations from a browser.

### CODE REVIEW

**Comment by jessevig** [comment]
Wow, this is incredible @cyber-raskolnikov! Thank you so much. I am away currently but will review and merge as soon as I can. Great work!!!

**Comment by cyber-raskolnikov** [comment]
Thanks! If you have any questions don't hesitate to contact me.

**Comment by jessevig** [comment]
Hi @cyber-raskolnikov I've merged your request into master, along with a minor change to specify font-family in the standalone HTML. Feel free to take a look if you like and share any feedback. I'll plan to update pypi version within the next few days. Thank you again!!!

**Comment by cyber-raskolnikov** [comment]
My pleasure!

**Comment by jessevig** [comment]
Just pushed out version 1.4.0. Thanks!!

**Pull request merged**
